# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:OTVs98lkMzl3srfrgjK5JuRUWQN7pUmowV+45Q4IP36yYVZWTSXCiA==,iv:fOMXAsHcX6XtZIZrv02VXoCFCNrtVQO31aglV9ogNQ8=,tag:79KmcfhxHVHNS+HA0+mRRQ==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMUZlR041MXFzR0lxejlp
        TFZXQWF0czR0MlJnVmJEV0NiVkJLUUNJUmkwCit3c2xWbWVPbGRaYzN2WG42Zlh4
        NUZQOXQ3bnVYbWtLNjBDa0hqUGZqS3cKLS0tIEF4U0tScXlEaUxkS2MzU2JyV1ov
        UVphTUs5bUZzWDkyajF6bnM2VG1BbjAKHRZdsA4eXC+34ngs7+IF3/btrOzDDzz+
        uajntYP961lBtmVIPxkWUHcTdLJDq/Tr6wIVKp2L+XMeikMDcwObOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T03:52:16Z"
  mac: ENC[AES256_GCM,data:Bf0aY53nPw2io+7WG1VZB6SKHsaRxpBtXTn0f2Svm7HUQr9/ipBDp0E67oHWa6clYIWvCmJuM66GryIPTxGqLsGsN5ENOuU/6w9GpnFQzt7oQmwwG0oopwNCSIpXNdL6l0NZUaYdi+HQtJVilFfIkb9erNktq/WLhlTXFx9a39Q=,iv:i5Urw+RBnfROSBd5a8GX7x17oEEgh3NBGSNMGZdYC0k=,tag:tNCs/hgAQZ/L82KkI5Ad6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
