# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:58ai+GlbXnH3Ff1Kq3VFTPaJ4JqTg7sd2+5AciERyhs=,iv:XIcjVlAkCQ5izvvkLC8wL10pU+ZdQ5GSHnmgH5sCzMQ=,tag:wAttOSTzia6+SE611nLf5Q==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTEYwb2VuVDdPbGFJZ2Vk
        a1B6UlkwQ3lHWnVPTmo3MlNsVXY4cEY4T0RJCkhKa2hrSGtBMm84cHBZKzYvSlFn
        K243ZHM3eTlYQXpZNFVmSWR6QnNIdkkKLS0tIGMvUkp6Y3Y3ZUlMNGFPbGpQcU1n
        TVFxSDh6NU9DR0dIbU1iK2VMdnVqTEUKhvracT/qeA3T813tCzi/tYqKFueKxtQJ
        rBf5GQ+MctBEWpId0f/4g9o/SsBYuW/jO3dIvr3y9vSLeXhMQlZXNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-30T20:08:16Z"
  mac: ENC[AES256_GCM,data:vyyEAXKNqaYrqvBMvNtMS9+RpE/2qFO99ZivJRGjvA6WEIRlzBkoHtGe5dtxEnKVFuf1nJqoTkDGv5ptibc/dd0RVza5mmr7Jz2LcaWgTeD5IUvHz3Xnx2JaR582hshN5bF1+1cobiEryJggHYW2egZEPYWeBZejbCeG/pxXRAA=,iv:VFXZDD//XensF18q3oxgl3CSlvYoiCLXQkDjC//iX2Q=,tag:smjbbXQnmwkF0ycIYs7bhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
