# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PMX+G1kMo9Xk3kvfPTGa8+a7Alsii5vDvuekybxr8qQ=,iv:GZMaObGmOcb6DyxIdkji4I6iZcFoq0hyjYuUm8+qaN4=,tag:QrG5JX7pnYBBhO1ub7WYmw==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDVESWZjZFRMdHJCdEtn
        c0Z2ZG1PTWh0Z3RFcVgvY2RWaFFVY0cydGc0CnNnS3I1SlhGeDRDWngvcFNxeDJj
        MGtyK2R6Z2lwRHRlY0lMWEg5b0l6NnMKLS0tIE5MOWpuM1dLcWpHT0RzTkN0VjVH
        R1JBdlR0am1WcXpwT215UWw4bHRneGcKLcaUxI8q0LxoH+imWUdwerNrTY5z2gBs
        Clg+XcDoj8zPaCatxAKs6c29whb9iHIfS6hdi4C9pOQDEhtopkeSZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T03:52:16Z"
  mac: ENC[AES256_GCM,data:b63JaTFhYY/Nzc+uKtfsIwvTyYT2Xwd26awCpH6WLhMYYHTudMNFpIT8Sd1YKX+F28inRcMxbwq1CAiwP+wA521h6vSFLa9qEu/xjvnv3cJdUpBrzPWRamzpnxSqe/0wt4Bl+5+KkYjtgEcwQBqaDEAiv/2Cnz6qrikMrsHd2Ms=,iv:BDO043rmKOoR7g8vzWy/6h+gNrrJMkM0sBQ1ggEox1Q=,tag:g6+BKvBIzOC+wQxNwi7kKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
