# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3/UM/apt82cU6pOZ2DWk6anr/K0Y6TWYfWw2au+/MPczh4VMQ1YMg0YvoT6NbyXTrb67OdsExN5V67wXV3y1ZmYU+D/adaAYwlKTJAE07ShpYKKcK1SBkMRJQ2TAZvEUQsDJESzgI4fYxHiKhGNCsXji+Fq5G3o7+6Y3U/nVI3HNEHn7pEKQvbOI+zC/2lovxEPuXD3rgOMiXoMywph3hPU7I9x+04B5s8HYdRwoabXVKLi8,iv:CcN5aO6BdLOWItleKR0uD+y0lViCKmOuYi289mO8Sns=,tag:pjk2RZoDeWCYeVJ1XT7Img==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWDNQa1ZRWHRvbWdvaGw0
        UDBaR3FTOVpoczdCZ1pTN1dOVkhXbUZuYWl3CjdYSFRWbmhpNGJaMnZKd2hodDVF
        OGJUUUNsRUlTK0JKd1JIdEt6cW1OU1UKLS0tIEwvMVE5K0dTYjBzd2h5bXRVSzRx
        K3RlYWVjODRTWUZiNU84Z2ViaCtLWm8K9fwhU9iY6k3v/liP2lGJSRFpu+nh8/yo
        cuBPaM/PbIqmvSqlfNJGsXswMDOP+cZhlF/7NuhySPkR8kjAX4JApw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-30T20:08:16Z"
  mac: ENC[AES256_GCM,data:mOpLT3FRUbPHGEWrRSBlAmygQ6uVB/iUGBIJZ6HZs4EYzRbImbUDZsaZMvSazQFrOOnTxe8v7keGLCCLQjO+Zz339OcExihfhKysj+Kkf0pCXDhWFm5TY57Pn+C1cFGazd67h1e/kDsZT8hDrgP1aEOnDjYGQyTe7zBQ2YyKQak=,iv:pr8PeNmc5NBbSsnB1ti0IxFaEq+7A2cPRa026yLOfPI=,tag:zO3WdiW7lNwzagq/x6v2/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
