# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KuDURPonW/g3VJ6709EKxpva+D4xT9mC0kbjv8Ho4XXb1WfmNT1pkt8Vf20YSxzAsBdvhrsoZ2wZ7r64Z90XIxhmTtWNCEc9ZGIMThEANFL0fVkbr+gKvfpw0mPNSAjTDvhIPmT4tQLx0M2OVBPgoprsfLT6EsmR909VR858e7VqZI06YuvakCfQ4hTeXa4BkFWP7TTV3Z1iJEkN0ZOenY5loDujTRJY2rRixtezqkcAvOcm,iv:z/o4H5Y8EZS9+7ODYC4kjUZDfPZZjxu6aX7CKjbGMvk=,tag:+gEpAcyzmeC7Ml4JqRqIVQ==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR0FlQ25UekYvRjJNVVZ0
        bDAzVVBGcWJtY21TbGdlYUpMNDZIa3kyc2dnCjNaUTF6c3lVbVIwaUdPdklSeXRh
        c2JjWWREb211UEVPMHl2U3VpQXBvSDQKLS0tIEpSREJSZ29ReVJnY1AzcU9UQkNM
        ejhZeEJzN1NzMUt6OGhrL2R4RnBHeFEKqHfipf7Ibk+D82hyLLM7fOG24/X5/u1P
        4dLt2rqjo6dXQB+0vBIAyGUkNb2hg9qBek1yLmUltmRFGpvpck80MQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-30T21:44:32Z"
  mac: ENC[AES256_GCM,data:enHhYmEWzgTSTH0oCmHlULlPp97JTiTMuWC4pLNf19ECd7YH7wEA90AC1VrWmgBsllrV/jfjVpguwP3RA/dFqybx2iQdQ+wFLEE5qe7dMT64VCgzWHjpkSR+uVNTW36gQbSzCbBL4GxT/z9nvEbh1Hm+Ze7dxmjIhkSbDwwifs8=,iv:IjWcDvBQM8yjtvapx0U7u9YhqFpbEdT6so8PHeFmDs4=,tag:7et6UBT2RFnIJKdNf3NzAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
