# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:+wX9gFcNZdiftPEkMxmuzDyITvYWwOAs5m5L0YDtafrIe78xiekrBTZKqJiyvhxFLI0D9Fk+nzkmzl4WqoNy0+1kkrzee5dok5pGcDYRvgJihsI2U72c02E3x+hulA3hy++eoo19klRIcuFSDd7G0wg5OIH7sPomCNtECTeCCMHiX1HDWVCwZot6m1HlCqMxNGtJM+TUP04p3q3YVWrWUI+nhIKoSMMjBaoZH5QtUjgyE+bn,iv:YKGMvoXIqwaur2i2lKud0KtdmoUj7rFIf69a/uXy1Bw=,tag:IHOo1jqlAnYMONIJ3spRmA==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYlhueHRka1JVUStrbUpG
        a01kOGNQSyt1em1ueEVJVkIxK0tSbTlMRnp3Ci8yZ2lwSzJvV014OVlTZ3k2Vk1r
        ekhTL2RaZjJsMmVhT3MzVHo4ckhoNjQKLS0tIHNBSzZOcWUzS2ZVM1ZLYUhxQzh2
        SFVqeXRnZ2FKSk45NEJYem14R0hPL2sKrugj82SjvxKc+UMl1OLnd6X5rYhyqZZN
        CjZZqixl+5g+abRDJONcaGq6Z3dvMUyAKg+lNxFJGp2KAziJ6hcYpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T13:24:48Z"
  mac: ENC[AES256_GCM,data:CjxwJySqXNq0F+t1nT/6TyUNs2SUikCfo11zibx5hBBwqY2uKY44hS45EUuRM9RN7iBp/8n4TwyzMmv4tfPQ/LhzFfRjpOVNw+4bPmwvIZPwKEyyfnOMzDAIEhF3PIGxyljKkGmqlC8qt0oSnXF2Y3wGfHbzur7HYM2T0q9XwzE=,iv:jZrtME7fqftWr5mG+4fRLHUWsrZuemScx7SSqrBxGn4=,tag:m3kUh5M7STorafn3uUjY+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
