# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:rZpF+S4EWaXFAgjd85OxiyIbHHd3t9tm5J6D/s2lQ3qS3NiOFwkWrQ==,iv:MFVluB41AtmN3TRaBsj3nV4CYVTd03LuJ7HsYS5wjzQ=,tag:1F3zLB08VOyjeWwzWkIAXw==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MEs5VkdKTlV2QmFkTTJi
        dktJNm0ycGVWV1Q0MDJnY2c4aThnY3VvT25FCmYyNUllRkd0eE1YdUMzK2NEYVM4
        RTFMMWJUNWJIZVNEZDMvWnBWV3BudVkKLS0tIFhQZi9zT0JJMHVsNEovZ1pncXBk
        c0ZhSnNWR2VFRGpiazU1WUdHakFuTncKWKjNY9xgkVPFCJYDL/0sY5xqoKJBKdbi
        QvT/8XF5et1RXZLjU0P3a2bmlvIbXSuZUEl63VU1D2VVDkP4qMo9aQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-30T20:08:16Z"
  mac: ENC[AES256_GCM,data:wK36fBMdRfrm4iYta2Q7xr+/XIF2H0c71neZbCgb9f56/iIqEoKkghCsHwew/3l5lGugO+QW8Jrxe8TgBpxCDd6zTb+HWQyTiiqRkUEH29lKd5ZDFqX1YnmOxUI3RXLRKKCC5ZZSfsj29fvBZ6OeUDgCJUNYgxaiOKS0UwfgMyo=,iv:UiJtajfGsQmLpMAAThcsNGvtF3BbkQMngScUq8+RfbM=,tag:MxuijSij2wVe1vnRolielw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
