# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7SdOj8gWo8SsYB8+Qyd/ENuYxvHNaZuCfiE1JDNJwFrqU0aztdhnaA==,iv:iZtSIFmXqBX+fKY+Bsd54l9m5a2GHmKk1mwETG1PO7M=,tag:4DuzJN05PoLjAQnFhPQHgg==,type:str]
sops:
  age:
    - recipient: age1f9yp9xhgk0w45umwncsjg4j8pux8mdw4uv83e73v30cn34xve99qk39cvl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aFlOZS8vOXdQWTJVMndJ
        eXE2Wk5KeFpCUzA2dnFWbmtMcVRKSm9LNkFjClYweStRcGN4ZEZuTUhndDRrbXBP
        RmsrenRlOHB4RmJUZEFtanVrbHVuVU0KLS0tIFk0OTJIWVIzR0tXRWZBL2Y3MnFQ
        RHZVOEplQ05IZVpSUi9GVmxCeitqZFUKUJwXzT/B27/cJ9kY1mGjl3JRsP706qj6
        pH2aYe0sblNlB3cXg1LtBNYShJT8NDl6zWnyE8p+oDybH5qULuYWyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T03:52:16Z"
  mac: ENC[AES256_GCM,data:Tro+jT8eTAtknqAojtP3l2lTqiL/RpknpFQhzWIYPIoYy/AmLzGPfEAs1zaRG527AiAeo4VQ2NGI6YVztJYY+2otVXpc/X55vxdAug0SE2Xww1ZldgN8s9ZJDvIA8L3/x+xb+XiNd/EHF2Ob0rPL02HR7V0r3P3qXs3vWlPeH6Y=,iv:jpCD5+jWCMYNrDLOmiV1IwvLr/RMBQfw8mGqiBl9nwE=,tag:V7W5VIZkbalSWiEKMoCuGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
